version: '2'
services:
  web:
    image: fpfis/httpd-php:7.3-dev
    working_dir: ${PWD}
    volumes:
    - ${PWD}:${PWD}
    - ${HOME}/.composer/auth.json:/root/.composer/auth.json
    - ${PWD}/resources/xDebug/xdebug.custom.ini:/etc/php/7.3/mods-available/xdebug.ini
    environment:
      DOCUMENT_ROOT: ${PWD}
      ASDA_USER:
      ASDA_PASSWORD:
      QA_API_BASIC_AUTH:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
      PHP_IDE_CONFIG: "serverName=Docker"
