command:
  toolkit:
    install-dump:
      options:
        dumpfile: ${toolkit.clone.dumpfile}
    run-deploy:
      options:
        sequence-file: ${toolkit.deploy.sequence_file}
        sequence-key: ${toolkit.deploy.sequence_key}
        config-file: ${toolkit.deploy.config_file}
